controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /
  controller: App\Controller\HomeController::home

app_login:
  path: /login
  controller: App\Controller\LoginController::login

_logout_main:
  path: /logout
  controller: App\Controller\LoginController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

reset-password:
  path: /reset-password
  controller: src\Controller\ResetPasswordController.php

app_trick_new:
 path: /newTrick
 controller: App\Controller\TrickController::new

app_category_new:
 path: /newCategory
 controller: App\Controller\CategoryController::new

app_trick_index:
 path: /indexTrick
 controller: App\Controller\TrickController::index

app_trick_show:
 path: /{id}/show
 controller: App\Controller\TrickController::show