controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /
  controller: App\Controller\HomeController::home

registration:
  path: /registration
  controller: App\Controller\UserController::new

app_login:
  path: /login
  controller: App\Controller\LoginController::login

_logout_main:
  path: /logout
  controller: App\Controller\LoginController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

reset-password:
  path: /reset-password
  controller: src\Controller\ResetPasswordController.php

app_trick_new:
 path: /new
 controller: App\Controller\TrickController::new
