controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /home
  controller: App\Controller\HomeController::home

registration:
  path: /registration
  controller: App\Controller\UserController::new
